//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextosGlobales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextosGlobales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TextosGlobales", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string TextBotonBuscar {
            get {
                return ResourceManager.GetString("TextBotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas....
        /// </summary>
        internal static string TextBotonColoumnas {
            get {
                return ResourceManager.GetString("TextBotonColoumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Excel.
        /// </summary>
        internal static string TextBotonExpoExcel {
            get {
                return ResourceManager.GetString("TextBotonExpoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final debe ser Igual/Posterior a la Inicial.
        /// </summary>
        internal static string TextCalendarFfFromMessage {
            get {
                return ResourceManager.GetString("TextCalendarFfFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final Incorrecta. Formato: yyyy-mm-dd.
        /// </summary>
        internal static string TextCalendarFfInvalidDateMessage {
            get {
                return ResourceManager.GetString("TextCalendarFfInvalidDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir Fecha Final.
        /// </summary>
        internal static string TextCalendarFfRequiredDateMessage {
            get {
                return ResourceManager.GetString("TextCalendarFfRequiredDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final hasta el 2099.
        /// </summary>
        internal static string TextCalendarFfToMessage {
            get {
                return ResourceManager.GetString("TextCalendarFfToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial a partir del 2011.
        /// </summary>
        internal static string TextCalendarFiFromMessage {
            get {
                return ResourceManager.GetString("TextCalendarFiFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial Incorrecta. Formato: yyyy-mm-dd.
        /// </summary>
        internal static string TextCalendarFiInvalidDateMessage {
            get {
                return ResourceManager.GetString("TextCalendarFiInvalidDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definir Fecha Inicial.
        /// </summary>
        internal static string TextCalendarFiRequiredDateMessage {
            get {
                return ResourceManager.GetString("TextCalendarFiRequiredDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial hasta el 2099.
        /// </summary>
        internal static string TextCalendarFiToMessage {
            get {
                return ResourceManager.GetString("TextCalendarFiToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        internal static string TextCiudad {
            get {
                return ResourceManager.GetString("TextCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final:.
        /// </summary>
        internal static string TextFechaFinal {
            get {
                return ResourceManager.GetString("TextFechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial:.
        /// </summary>
        internal static string TextFechaInicial {
            get {
                return ResourceManager.GetString("TextFechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concentrador.
        /// </summary>
        internal static string TextLblConcentrador {
            get {
                return ResourceManager.GetString("TextLblConcentrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay información según los filtros.
        /// </summary>
        internal static string TextMsgRepNoData {
            get {
                return ResourceManager.GetString("TextMsgRepNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ASDU.
        /// </summary>
        internal static string TextoASDU {
            get {
                return ResourceManager.GetString("TextoASDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        internal static string TextoCalleKra {
            get {
                return ResourceManager.GetString("TextoCalleKra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causa Activación.
        /// </summary>
        internal static string TextoCausaActivacion {
            get {
                return ResourceManager.GetString("TextoCausaActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cicuito.
        /// </summary>
        internal static string TextoCircuito {
            get {
                return ResourceManager.GetString("TextoCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        internal static string TextoCodigoEquipo {
            get {
                return ResourceManager.GetString("TextoCodigoEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código FWT.
        /// </summary>
        internal static string TextoCodigoFWT {
            get {
                return ResourceManager.GetString("TextoCodigoFWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alarma.
        /// </summary>
        internal static string TextoFalla {
            get {
                return ResourceManager.GetString("TextoFalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fase.
        /// </summary>
        internal static string TextoFase {
            get {
                return ResourceManager.GetString("TextoFase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string TextoFecha {
            get {
                return ResourceManager.GetString("TextoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        internal static string TextoFechaClear {
            get {
                return ResourceManager.GetString("TextoFechaClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Instalacion.
        /// </summary>
        internal static string TextoFechaInstalacion {
            get {
                return ResourceManager.GetString("TextoFechaInstalacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Registro.
        /// </summary>
        internal static string TextoFechaRegistro {
            get {
                return ResourceManager.GetString("TextoFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        internal static string TextoGenericoId {
            get {
                return ResourceManager.GetString("TextoGenericoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string TextoGenericoValor {
            get {
                return ResourceManager.GetString("TextoGenericoValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificador.
        /// </summary>
        internal static string TextoIdentificadorEquipo {
            get {
                return ResourceManager.GetString("TextoIdentificadorEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        internal static string TextoLatitud {
            get {
                return ResourceManager.GetString("TextoLatitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud.
        /// </summary>
        internal static string TextoLongitud {
            get {
                return ResourceManager.GetString("TextoLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo.
        /// </summary>
        internal static string TextoNodo {
            get {
                return ResourceManager.GetString("TextoNodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número.
        /// </summary>
        internal static string TextoNumeroDireccion {
            get {
                return ResourceManager.GetString("TextoNumeroDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tramo.
        /// </summary>
        internal static string TextoSeccionTramo {
            get {
                return ResourceManager.GetString("TextoSeccionTramo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segs.
        /// </summary>
        internal static string TextoSecs {
            get {
                return ResourceManager.GetString("TextoSecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundos.
        /// </summary>
        internal static string TextoSegundos {
            get {
                return ResourceManager.GetString("TextoSegundos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial.
        /// </summary>
        internal static string TextoSerialEquipo {
            get {
                return ResourceManager.GetString("TextoSerialEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serial FWT.
        /// </summary>
        internal static string TextoSerialFWT {
            get {
                return ResourceManager.GetString("TextoSerialFWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subestación.
        /// </summary>
        internal static string TextoSubestacion {
            get {
                return ResourceManager.GetString("TextoSubestacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Circuito.
        /// </summary>
        internal static string TextoTipoCircuito {
            get {
                return ResourceManager.GetString("TextoTipoCircuito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scada.
        /// </summary>
        internal static string TextoTituloScada {
            get {
                return ResourceManager.GetString("TextoTituloScada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Corriente (A).
        /// </summary>
        internal static string TextoValorCorriente {
            get {
                return ResourceManager.GetString("TextoValorCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión FW.
        /// </summary>
        internal static string TextoVersionFw {
            get {
                return ResourceManager.GetString("TextoVersionFw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FirmwareEquipo.
        /// </summary>
        internal static string TextoVersionFwERT {
            get {
                return ResourceManager.GetString("TextoVersionFwERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión.
        /// </summary>
        internal static string TextoWordVersion {
            get {
                return ResourceManager.GetString("TextoWordVersion", resourceCulture);
            }
        }
    }
}
